source 'https://github.com/CocoaPods/Specs.git'

# inhibit_all_warnings!
use_frameworks!

def testing_pods
	pod 'SSZipArchive', :path => '..'
end

target 'ObjectiveCExample' do
  testing_pods
  platform :ios
end

target 'ObjectiveCExampleTests' do
  testing_pods
  platform :ios
end
