name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: 
      - master
    tags:
      - '*'
jobs:
  # available images: https://github.com/actions/runner-images
  
  # oldest GitHub targets
  macos-13:
    runs-on: ${{matrix.OS}}
    strategy:
      fail-fast: false
      matrix:
        OS: [macOS-13]
        SDK: ["macosx"]
    steps:
    - uses: actions/checkout@v4 # https://github.com/actions/checkout
    - name: Install dependencies
      run: |
        pushd Example
        pod install
        popd  
    - name: Build and test
      run: |
        if [ ${{ matrix.SDK }} == "macosx" ]; then
          SCHEME="ObjectiveCExample_macOS"
          PLATFORM="macOS"
          ARCH="x86_64"
          DESTINATION="platform=$PLATFORM,arch=$ARCH"
        fi
        
        # build and test
        CONFIGURATION="Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES"
        xcodebuild -workspace Example/ZipArchiveExample.xcworkspace -scheme $SCHEME -destination "$DESTINATION" -configuration $CONFIGURATION test

  # newest GitHub targets
  macos-15:
    runs-on: ${{matrix.OS}}
    strategy:
      fail-fast: false
      matrix:
        OS: [macOS-15]
        SDK: ["appletvsimulator", "iphonesimulator", "watchsimulator", "xrsimulator"]
    steps:
    - uses: maxim-lobanov/setup-xcode@v1 # https://github.com/maxim-lobanov/setup-xcode
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v4 # https://github.com/actions/checkout
    - name: Install dependencies
      run: |
        pushd Example
        pod install
        popd
    - name: Build and test
      run: |
        if [ ${{ matrix.SDK }} == "appletvsimulator" ]; then
          SCHEME="ObjectiveCExample_tvOS"
          SDK="appletvsimulator"
          PLATFORM="tvOS Simulator"
          DEVICE="Apple TV 4K (3rd generation) (at 1080p)"
          DESTINATION="platform=$PLATFORM,name=$DEVICE"
        fi
        if [ ${{ matrix.SDK }} == "iphonesimulator" ]; then
          SCHEME="ObjectiveCExample_iOS"
          SDK="iphonesimulator"
          PLATFORM="iOS Simulator"
          DEVICE="iPhone 16 Pro Max"
          DESTINATION="platform=$PLATFORM,name=$DEVICE"
        fi
        if [ ${{ matrix.SDK }} == "watchsimulator" ]; then
          SCHEME="ObjectiveCExample_watchOS"
          SDK="watchsimulator"
          PLATFORM="watchOS Simulator"
          DEVICE="Apple Watch Ultra 2 (49mm)"
          DESTINATION="platform=$PLATFORM,name=$DEVICE"
        fi
        if [ ${{ matrix.SDK }} == "xrsimulator" ]; then
          SCHEME="ObjectiveCExample_visionOS"
          SDK="xrsimulator"
          PLATFORM="visionOS Simulator"
          DEVICE="Apple Vision Pro"
          DESTINATION="platform=$PLATFORM,name=$DEVICE"
        fi

        # build and test
        CONFIGURATION="Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES"
        xcodebuild -workspace Example/ZipArchiveExample.xcworkspace -scheme $SCHEME -sdk $SDK -destination "$DESTINATION" -configuration $CONFIGURATION test
